version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - TEST_DB_USER=${TEST_DB_USER}
      - TEST_DB_HOST=${TEST_DB_HOST}
      - TEST_DB_PASSWORD=${TEST_DB_PASSWORD}
      - TEST_DB_PORT=${TEST_DB_PORT}
      - TEST_DB_NAME=${TEST_DB_NAME}
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
